spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ghostnet_test
    username: spring-user
    password: spring-password
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always
      platform: mysql
logging:
  level:
    org.hibernate.SQL: DEBUG
