spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ghostnet_test
    username: testuser
    password: testpass
  jpa:
    hibernate:
      ddl-auto: create-drop
logging:
  level:
    org.hibernate.SQL: DEBUG
